### ISSUE TITLE
Gunfish render on top of cannons

### ISSUE THREAD

**Issue by Jeffrey-Wang** [ryanakann/Gunfish#40]
Gunfish should either render on the Gunfish sorting layer, or if that's not possible with LineRenderer see how else to fix this.

**Comment by WyotJunctor** [comment]
We just need to change the sorting layers of things. I propose background, midground-behind, gunfish, midground-front, foreground

**Comment by Jeffrey-Wang** [comment]
I have fixed the sorting layers already but the gunfish do not render inside their designated sorting layer. We need to determine if we can fix that or find another workaround
